### ISSUE TITLE
Make it work without phrases and word groups

### ISSUE THREAD

**Issue by ProgmasterX** [golosio/annabell#24]
My suggestion is to make it remember raw sentences and learn language from them by using only .rw and .x

**Comment by golosio** [comment]
Thank you for giving me the opportunity to clarify this point.
I understand that from a machine learning perspective it would be much more interesting to have a model that can learn without guidance, which could be trained from a plain question/answer database. However you should keep in mind that Annabell is not an engineering solution to the problem of human-machine dialogue, it is a cognitive model of language development, targeted at a specific child age range (3-4 years), and designed to help understand how we develop our language processing skills, and how our high-level cognitive functions are related to low-level neural processes (See also one of my answers to Issue 1 before devoting time to this project:
https://github.com/golosio/annabell/issues/4#issuecomment-163859240). To be more specific, I and my colleagues do not believe that a little child could learn to communicate through natural language just by being exposed to a huge question/answer corpora, without guidance. Rather, she mainly learns through child-parent cooperative dyadic relationship, as well as child-peer interactions. This interactions are not based only on verbal information, but also on nonverbal information, which is communicated through prosody, volume and frequency of the voice, facial expressions, gestures. The guidance procedure that we are using is an extremely simplified surrogate of such mechanisms. An improvement of the model, for me, would be to make this guidance procedure more similar to that between parent and child, but as I said this is very difficult because it would involve the use of nonverbal information too. Actually I am also working on cognitive models of unsupervised language learning, which becomes more important in the following stages of language development (starting at 4-5 years). But that is another project, and it is also oriented to cognitive models of language development, not to machine learning.
