### ISSUE TITLE
how do i faster training

### ISSUE THREAD

**Issue by RoboMantis** [golosio/annabell#28]
./training_run >> something.text
I tried the pipe command so the training text doesn't show up to speed it up but it didn't work.
There's gotta be a quick fix for this from a fellow technician to speed up the training time?

**Comment by RoboMantis** [comment]
the text runs in terminal and slows down training, can anyone give me a hint?

**Comment by golosio** [comment]
As it seems that you are from the machine learning community, you should have a look at one of my answers to Issue 1 before devoting time to this project:
#4 (comment)
Annabell is neither a chatbot, nor an application-oriented dialog system. It is a cognitive model, designed to help understand how we develop our language processing skill and how such skills are related to neural processes that take place in our brain. This means that we are not simply simulating the way how humans hold a dialog, we are trying to simulate neural processes that support language development. The computational resources needed for this are huge. Compared to other large-scale neural architectures of similar size, Annabell is faster by about three orders of magnitude, because it takes advantage of a sparse-signal representation. But still, it cannot be compared to other technical solutions to the problem of human machine dialog. The text running in the terminal only takes a minimal fraction of execution time during training. Most of the time is devoted to the propagation of the signal in the neural network.
