### ISSUE TITLE
There is no configure file.

### ISSUE THREAD

**Issue by plotkin1996** [golosio/annabell#30]
No ./configure file is provided in the repository.

**Comment by golosio** [comment]
This is the answer of one of my collaborators, more experienced than me on github and autobuild:
"Basically the idea is that git only indexes the files that are essential to generate a working build. Since files like configure and Makefile.in can be generated via ‘autoreconf -i’ there is no need to add them to the git repository. This is actually quite standard, which is why I didn’t bother adding this to the installation notes."
